### PR TITLE
convert to origami 2.0 component

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by JakeChampion** [comment]
The primary mixin test in origami-build-tools v11 has surfaced the fact that the mixin `oSubsCard` does not follow the origami convention of a "primary mixin"
-- This means it will also not work with origami-build-service v3 as that [assumes the mixin works as a 'primary mixin' ](https://github.com/Financial-Times/origami-build-service/blob/03ef473b493c59b5d8aafdfba1fd2e3b1a9dafd6/lib/middleware/v3/createEntryFileSass.js#L16-L25).

**Comment by JakeChampion** [comment]
This is now ready for a review 👍

**Comment by notlee** [comment]
This looks great :) Would you mind updating the README Sass section too? It still mentions silent mode and doesn't show a primary mixin example / options

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v5.0.0 :tada:

**Pull request merged**
